#!/bin/sh
# Fallback for type sharing. Normally the app imports ../src/lib/types.ts directly via
# the `@shared/types` alias (metro.config.js + tsconfig.json). If that ever breaks
# (e.g. building mobile/ outside the monorepo), run this script to copy the file in,
# then point the alias at ./shared/types.ts in BOTH tsconfig.json and metro.config.js.
set -eu
here="$(cd "$(dirname "$0")/.." && pwd)"
src="$here/../src/lib/types.ts"
dest="$here/shared/types.ts"
mkdir -p "$here/shared"
{
  echo "// GENERATED by scripts/sync-types.sh from src/lib/types.ts — do not edit."
  cat "$src"
} > "$dest"
echo "Copied $src -> $dest"
